development:
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: esport42
  username: esport42
  password: esport42
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: UTF8
  host: <%= begin IO.read("/home/ubuntu/apps/esport42/shared/.db_ip_adress") rescue "" end %>
  port: 5432
  database: <%= begin IO.read("/home/ubuntu/apps/esport42/shared/.db_database") rescue "" end %>
  username: <%= begin IO.read("/home/ubuntu/apps/esport42/shared/.db_username") rescue "" end %>
  password: <%= begin IO.read("/home/ubuntu/apps/esport42/shared/.db_password") rescue "" end %>
  pool: 5
  timeout: 5000
