class AddAttributesToUser < ActiveRecord::Migration
  def change
    add_column :users, :skype_id, :string, default: ""
    add_column :users, :email_secondary, :string, default: ""
    add_column :users, :phone_mobile, :string, default: ""
    add_column :users, :phone_home, :string, default: ""
    add_column :users, :steam_id, :string, default: ""
    add_column :users, :battlenet_id, :string, default: ""
    add_column :users, :origin_id, :string, default: ""
    add_column :users, :maniaplanet_id, :string, default: ""
    add_column :users, :xbox_live, :string, default: ""
    add_column :users, :sony_psn, :string, default: ""
    add_column :users, :website_url, :string, default: ""
    add_column :users, :facebook_private_url, :string, default: ""
    add_column :users, :facebook_gamer_url, :string, default: ""
    add_column :users, :youtube_url, :string, default: ""
    add_column :users, :twitch_url, :string, default: ""
    add_column :users, :googleplus_url, :string, default: ""
    add_column :users, :sponsor, :string, default: ""
    add_column :users, :quote, :string, default: ""
    add_column :users, :pc_cpu, :string, default: ""
    add_column :users, :pc_ram, :string, default: ""
    add_column :users, :pc_graphic_card, :string, default: ""
    add_column :users, :pc_motherboard, :string, default: ""
    add_column :users, :pc_keyboard, :string, default: ""
    add_column :users, :pc_mouse, :string, default: ""
    add_column :users, :pc_mousepad, :string, default: ""
    add_column :users, :pc_screen, :string, default: ""
    add_column :users, :pc_internet, :string, default: ""
    add_column :users, :pc_harddisk, :string, default: ""
    add_column :users, :pc_soundcard, :string, default: ""
    add_column :users, :pc_cpu_fan, :string, default: ""
    add_column :users, :pc_computer_case, :string, default: ""
    add_column :users, :pc_alim, :string, default: ""
    add_column :users, :pc_os_sytem, :string, default: ""
    add_column :users, :pc_smarphone, :string, default: ""

  end
end
